apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: hello-node
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: hello-node
      name: hello-node
    spec: 
      containers: 
        - 
          image: "gcr.io/trusty-drive-228822/hellonode:1.0.0"
          imagePullPolicy: Always
          name: backend
          ports: 
            - 
              containerPort: 8080
              name: hello-node
          resources: 
            limits: 
              memory: 2Gi
            requests:
              memory: 2Gi
          progressDeadlineSeconds: 30

